### ISSUE TITLE
energy saved update

### ISSUE THREAD

**Issue by tikismoke** [XavierBerger/Solar-Router-for-ESPHome#16]
https://github.com/XavierBerger/Solar-Router-for-ESPHome/blob/22c3912fd9d19e2ae506fbb93b6e8a1131450b1b/solar_router/energy_saved_counter_theorical.yaml#L18

I think we should update this everytime the regulator_opening.state change, not every 30s.

Maybe just duplicate update script energy_saved_counter from energy_saved_counter_none with the lambda from energy_saved_counter_theorical
like done here: https://github.com/XavierBerger/Solar-Router-for-ESPHome/blob/22c3912fd9d19e2ae506fbb93b6e8a1131450b1b/solar_router/solar_router_engine.yaml#L50

May be not so easy ;)

**Comment by XavierBerger** [comment]
This piece of code is in development stage. I didn't test it yet.

In my algorithm, I planned to increment `energy_saved` every time the Triac opening is modified. This counter is an incremental counter. To avoid generating too much data, the idea is to publish the energy saved less frequently... every 30sec in my prototype.

**Comment by XavierBerger** [comment]
@tikismoke I did update the counter of energy saved (calculated ... and not measured) on branch [feature/report_energy_diverted](https://github.com/XavierBerger/Solar-Router-for-ESPHome/tree/feature/report_energy_diverted). 
If you have time, your feedback is welcome.

**Comment by XavierBerger** [comment]
Branch merged.

**Comment by tikismoke** [comment]
Will test when swimming pool on.

The other solar router runs fa1tb to use multisinus mode on the SSR.
