### ISSUE TITLE
Rename sensor/command/light/etc

### ISSUE THREAD

**Issue by tikismoke** [XavierBerger/Solar-Router-for-ESPHome#20]
All name in config should be replaced by device name or any other variable present in substitution

For exemple
`    name: "Activate Solar Routing"`
should be replaced by:
`    name: "{name} Activate Solar Routing"
`

Why?
Because when you create another solar router you get that sort of sensor/command:
`switch.activate_solar_routing_2`
and 
`switch.activate_solar_routing_3`
for the 3rd one :(

This is really anoying to use then in automation and remmeber that no name is for swimming pool, _2 for heating bathroom1 and _3 for the other bathroom.

**Comment by XavierBerger** [comment]
@tikismoke I did apply your proposal.  
Can you give me some feedback about my implementation?  
If it works, I'll merge it in the main branch.

**Comment by XavierBerger** [comment]
hummm... is this modification really necessary, I already have a prefix on every sensor which is added automatically.

The prefix comes from the name stated here: 

```yaml
esphome:
  name: solarrouter
  friendly_name: SolarRouter
```

**Comment by tikismoke** [comment]
Yes because no sensor are you sing this prefix and I got _2 or _3 on the two other devices i prepared

**Comment by XavierBerger** [comment]
@tikismoke I also have 2 solar routers in my setup (mainly for development).

I use [esp32-standalone.yaml](https://github.com/XavierBerger/Solar-Router-for-ESPHome/blob/feat/improve_reliability/esp32-standalone.yaml) and [esp8285-power-meter-proxy.yaml](https://github.com/XavierBerger/Solar-Router-for-ESPHome/blob/feat/improve_reliability/esp8285-power-meter-proxy.yaml) at the same time.

I have then 2 sensors clearly identified by their name as prefix:
![image](https://github.com/user-attachments/assets/467e3601-32c7-443a-95cc-074428336408)

Can you check your configuration... As I can't reproduce your issue, it is difficult to find a root cause and a fix.

**Comment by tikismoke** [comment]
> @tikismoke I also have 2 solar routers in my setup (mainly for development).
> Can you check your configuration... As I can't reproduce your issue, it is difficult to find a root cause and a fix.
> 
> 

Could you look at all other sensor/cmd of your device?

**Comment by tikismoke** [comment]
Yes because no sensor are you sing this prefix and I got _2 or _3 on the two other devices i prepared this one for example:
![Screenshot_20241025-174850.png](https://github.com/user-attachments/assets/65577d8f-3c9c-4c40-9329-5a1c656e3eda)

**Comment by XavierBerger** [comment]
Aller, on bascule en français, ce sera plus facile de se comprendre :wink: 

J'ai bien compris ton problème de nommage de sensors dans ton installation. Je ne remets pas en cause ce que tu constates, mais je n'arrive pas à le reproduire. 
J'ai vérifié de mon côté et tous mes sensors sont préfixés. J'ai même essayé d'appliquer ta proposition et je me retrouve avec des sensors ave `id:sensor.solarrouter_name_real_power ` et `friendly_name:"Solar Router name Real Power"`... donc ça ne marche pas.

Pour progresser, peux-tu me faire parvenir tes fichiers YAML complets ? 

J'essayerais de les installer sur mon routeur pour voir ce que ça donne et si j'arrive à la même situation.

**Comment by tikismoke** [comment]
C'est bizarre ça.
Le {name} sert a faire la substitution (que tu declare bien au départ.
Si y en a pas dans le nom du sensor/Switch ou autre, je vois pas comment il fait la substitution justement en prefixant du coup.

**Comment by tikismoke** [comment]
https://github.com/XavierBerger/Solar-Router-for-ESPHome/issues/15#issuecomment-2218549018

Voici le code que j'utilise sur mes 2 routeurs.
A l'adresse IP prêt et l'id de la sonde onewire

**Comment by tikismoke** [comment]
![Screenshot_20241026-172047-629.png](https://github.com/user-attachments/assets/901cb26a-fce7-4143-b0dd-9c29dd4bdb7e)

Tiens voilà le résultat sur le routeur du chauffage 1.

Les capteurs issue de GitHub sont tous avec nomcapteur_2 ceux issue de mon code ou le {name} est utilisé ne l'ont pas et son pr fixer par le name_

**Comment by tikismoke** [comment]
Ce qui est marrant, c'est qu'on dirait que les sensor pur ça fonctionne :
![Screenshot_20241026-172737-988.png](https://github.com/user-attachments/assets/f444ceaf-bf87-4267-8f8b-cae4368bfdb0)

Genre real power ça rajoute bien le nom devant.

**Comment by tikismoke** [comment]
Pourtant les number, y a deux comportements différents.

**Comment by XavierBerger** [comment]
J'ai reproduit ton problème en supprimant `friendly_name`. Sans `friendly_name`, les entités ne sont pas préfixées.  
Dans ta configuration, tu as défini la variable `friendly_name` mais tu ne l'affectes pas à `esphome`:

```
esphome:
  name: solarrouter
  friendly_name: ${friendly_name}     # <- c'est cette ligne qui manque dans ta configuration
```

**Comment by tikismoke** [comment]
Bon ben je suis bon pour me coltiner une petite modif dans esphome on dirait.

C'est pas comme si j'avais ~90 devices sous esphome heureusement que y a les includes :)

En tout cas merci j'ai appris un truc.
Surement un changelog que j'ai raté car ça me dit rien qu'HA s'en servait pour préfixer tout seul.
