### ISSUE TITLE
Activate toggle goes OFF

### ISSUE THREAD

**Issue by nos317** [XavierBerger/Solar-Router-for-ESPHome#26]
Hi, after 30sec of regulation (when honestly de real_power is very difficult to stabilizing), the regulation stops, and "activate toggle" goes automatically OFF.

One more question, why PWM Frequency set to 330ms? Isn't multiple of 50Hz.

Thanks a lot
P.S. great work, can't find anything better online

**Comment by XavierBerger** [comment]
@nos317 Can you share your configuration?   
I experienced such an issue due to the watchdog when the http server providing the power information is too slow.

Thanks for the PS :smile: ... but did you try this solar router : https://yasolr.carbou.me/. Our hardware are compatibles.

**Comment by nos317** [comment]
It seems very good site!

But... Unfortunately that router doesn't work with HA+ESP32+SSR.

The "Home assistant" version is only with shelly 0/1-10V plus dimmer.

Il gio 7 nov 2024, 20:37 Xavier Berger ***@***.***> ha
scritto:
